project_id = "rwfqswiwalygzfojyeqk"

[functions.socratic-oracle]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.generate-narrative]
verify_jwt = false

[functions.ai-nodes]
verify_jwt = false

[functions.ai-edges]
verify_jwt = false

[functions.ai-questions]
verify_jwt = false

[functions.ai-episodes]
verify_jwt = false

[functions.ai-dialogue-summary]
verify_jwt = false

[functions.ai-curate-text]
verify_jwt = false

[functions.podcast-storage]
verify_jwt = true
